blank_issues_enabled: true
contact_links:
  - name: FulibScenarios on StackOverflow
    url: https://stackoverflow.com/questions/tagged/fulibscenarios
    about: Please ask and answer questions here (make sure to add the 'fulibscenarios' tag).
